# Generated by Django 2.0.2 on 2018-03-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('deadline', models.DurationField()),
                ('interest', models.FloatField()),
                ('loanDate', models.DateField()),
                ('loan_options', models.CharField(choices=[('normal', 'Normal Loan'), ('emergency', 'Emergency Loan'), ('fees', 'Fees Loan')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccName', models.CharField(max_length=20)),
                ('userAccNo', models.IntegerField()),
                ('userAccBal', models.IntegerField()),
                ('groupAccNo', models.IntegerField()),
                ('acc_options', models.CharField(choices=[('shares', 'shares account'), ('deposits', 'deposits account'), ('withdrawal deposits', 'withdrawal deposits account')], max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_shares', models.IntegerField()),
                ('savingsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.Savings')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalDeposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('acc_options', models.CharField(choices=[('gold', 'Gold Account'), ('silver', 'Silver account'), ('bronze', 'Bronze account')], max_length=50)),
                ('savingsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.Savings')),
            ],
        ),
        migrations.AddField(
            model_name='loans',
            name='savingsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.Savings'),
        ),
        migrations.AddField(
            model_name='deposits',
            name='savingsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.Savings'),
        ),
    ]
