# Generated by Django 2.0.2 on 2018-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('userAccName', models.CharField(max_length=20, null=True)),
                ('userAccNo', models.IntegerField(null=True)),
                ('accType', models.CharField(max_length=30, null=True)),
                ('groupAccNo', models.IntegerField(null=True)),
                ('userAccBal', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('shares', models.IntegerField(null=True)),
                ('activity', models.CharField(max_length=200)),
                ('userAccBankBranch', models.CharField(max_length=20, null=True)),
                ('activityType', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
