# Generated by Django 2.0.2 on 2018-02-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('userAccNo', models.IntegerField()),
                ('userAccType', models.CharField(max_length=10)),
                ('userAccName', models.CharField(max_length=50)),
                ('userAccBankBranch', models.CharField(max_length=20)),
                ('savingsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.Savings')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('userAccName', models.CharField(max_length=20, null=True)),
                ('userAccNo', models.IntegerField(null=True)),
                ('accType', models.CharField(max_length=30, null=True)),
                ('groupAccNo', models.IntegerField(null=True)),
                ('userAccBal', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('shares', models.IntegerField(null=True)),
                ('userAccBankBranch', models.CharField(max_length=20, null=True)),
                ('activityType', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
