# Generated by Django 2.0.2 on 2018-02-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccName', models.CharField(max_length=20)),
                ('userAccNo', models.IntegerField()),
                ('userAccBal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Date this was published')),
                ('amount', models.IntegerField(max_length=6)),
                ('userAccNo', models.IntegerField(max_length=7)),
                ('userAccType', models.CharField(max_length=10)),
                ('userAccName', models.CharField(max_length=50)),
                ('userAccBankBranch', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='savings',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.Transfer'),
        ),
    ]
