# Generated by Django 2.0.2 on 2018-02-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20180209_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='savings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
